//
// Created by wanjiangzhi on 2026/4/4.
//

#ifndef ZCLIBLOG_LOGGER_CONFIGURATIONS_H
#define ZCLIBLOG_LOGGER_CONFIGURATIONS_H

// 是否为Logger添加默认csnprintf formatter
#define ZCLIBLOG_LOGGER_CONFIGURATIONS_DEFAULT_CSNPRINTF true

// 异步Logger默认线程数量
#define ZCLIBLOG_LOGGER_CONFIGURATIONS_ASYNC_THREAD_NUM 1

#endif //ZCLIBLOG_LOGGER_CONFIGURATIONS_H
